### ISSUE TITLE
[plymouth-kcm]: allow to get and install new plymouth theme from store.kde.org

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-general#47]
Category is here: https://store.kde.org/browse/cat/108/ord/latest/

**Comment by notmart** [comment]
This probably makes necessary a KCM for selecting the plymouth theme. @apachelogger : what would be needed for that? could a thing like that work cross-distro?

**Comment by star-buck** [comment]
It could be an extra kcm, like samba mounter or systemd.

**Comment by apachelogger** [comment]
@notmart Different distributions put the themes in different directories and use different tools to pack their initramfs (and by extension the way the default theme is set is different as well). So, if one were to create a KCM it would have to outsource that stuff to a distro plugin or helper binary.

e.g. 
```
DistroPlugin
  install(path_to_tmpdir)
  list_installed_theme_paths()
  select(theme_path) # also rebuilds initramfs
```

**Comment by apachelogger** [comment]
As an additional thought. It definitely should be kept separate from the default KCMs. For one, it would only work if the distro has a backing plugin. More importantly, since this ultimately is tinkering with the initrd there's potential for making the system unbootable if things go wrong.

**Comment by notmart** [comment]
if it's just different paths, could them be specified at built time in cmake and be enough?
anyways, if this is still a priority I can try to write one that would be shipped as a standalone repository and would probably be pretty much specific for neon/maui/ubuntu type distros, with other distros probably having to change something

**Comment by notmart** [comment]
if i understood correctly, all i need would be the folder where themes are installed (/usr/share/plymouth/themes/ or whatever) to actually install new ones, then to list and install the root command plymouth-set-default-theme should work everywhere?

**Comment by star-buck** [comment]
Yeah, if we could do an "apply" button that would execute that command
after pwd authentication, that would be great. So people can install more
themes, remove themes plus set and see which theme is currently default.

**Comment by star-buck** [comment]
A bit like sddm, which also needs pwd to apply.

**Comment by apachelogger** [comment]
@notmart the theme installation path you could actually get from plymouth's pkg-config info IIRC. plymouth-set-default-theme is not a thing unless you expect distros to provide one for the kcm. 

That could work.

WRT removal, do note that removing a theme that is provided by a package is not persistent as updates to the package would bring back the theme.

**Comment by star-buck** [comment]
Yeah, removing would be the same like for wallpapers then, only possible
for those installed via GHNS.

**Comment by notmart** [comment]
on knewstuff side.. https://api.kde-look.org/ocs/v1/content/categories doesn't seem to list the category of plymouth themes? i can't seem to get to it via api

**Comment by star-buck** [comment]
Should work now?

**Comment by star-buck** [comment]
Okay, can take some time before being visible...

**Comment by notmart** [comment]
themes are correctly listed now

**Comment by notmart** [comment]
I have a prototype at
https://cgit.kde.org/scratch/mart/plymouthkcm.git/
I would like a first round of testing on a real distribution.. @apachelogger: could it be packaged on neon?
It's still very rough, but  it appears to have a correct basic operation: switching/install/uninstall themes, all with authentication when apply is pressed.
some problems are still known
* some theme from kdelook won't work, have to investigate if it's how they are installed or if they are wrong/outdated
* themes don't come with a thumbnail, so previews are still empty
* due to its nature is a quite dangerous tool, so always to be used with care

**Comment by apachelogger** [comment]
https://phabricator.kde.org/T4881

**Comment by notmart** [comment]
latest version, takes screenshots from knewstuff, install, uninstall and applying themes should work
![screenshot_20161220_134643](https://cloud.githubusercontent.com/assets/4526371/21351033/e524c378-c6ba-11e6-9fc4-b9c07220bd34.png)

**Comment by star-buck** [comment]
That looks really nice!

**Comment by notmart** [comment]
the new repo plymouth-kcm is up
the package should be changed from being built from scratch/mart/plymouthkcm to plymouth-kcm.git
@apachelogger can you do it? (as i can't push to pangea-conf-projects, and probably neither i should :p)

**Comment by star-buck** [comment]
done.
